/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as FusionRouteImport } from './routes/fusion'
import { Route as EquipmentsRouteImport } from './routes/equipments'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonasIndexRouteImport } from './routes/personas/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as EnemiesIndexRouteImport } from './routes/enemies/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as PersonasPersonaIdRouteImport } from './routes/personas/$personaId'
import { Route as LocationsLocationIdRouteImport } from './routes/locations/$locationId'
import { Route as EnemiesEnemyIdRouteImport } from './routes/enemies/$enemyId'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$characterId'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const FusionRoute = FusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentsRoute = EquipmentsRouteImport.update({
  id: '/equipments',
  path: '/equipments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasIndexRoute = PersonasIndexRouteImport.update({
  id: '/personas/',
  path: '/personas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnemiesIndexRoute = EnemiesIndexRouteImport.update({
  id: '/enemies/',
  path: '/enemies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasPersonaIdRoute = PersonasPersonaIdRouteImport.update({
  id: '/personas/$personaId',
  path: '/personas/$personaId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnemiesEnemyIdRoute = EnemiesEnemyIdRouteImport.update({
  id: '/enemies/$enemyId',
  path: '/enemies/$enemyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/equipments': typeof EquipmentsRoute
  '/fusion': typeof FusionRoute
  '/items': typeof ItemsRoute
  '/quests': typeof QuestsRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/enemies/$enemyId': typeof EnemiesEnemyIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/personas/$personaId': typeof PersonasPersonaIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/enemies/': typeof EnemiesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/personas/': typeof PersonasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/equipments': typeof EquipmentsRoute
  '/fusion': typeof FusionRoute
  '/items': typeof ItemsRoute
  '/quests': typeof QuestsRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/enemies/$enemyId': typeof EnemiesEnemyIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/personas/$personaId': typeof PersonasPersonaIdRoute
  '/characters': typeof CharactersIndexRoute
  '/enemies': typeof EnemiesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/personas': typeof PersonasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/equipments': typeof EquipmentsRoute
  '/fusion': typeof FusionRoute
  '/items': typeof ItemsRoute
  '/quests': typeof QuestsRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/enemies/$enemyId': typeof EnemiesEnemyIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/personas/$personaId': typeof PersonasPersonaIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/enemies/': typeof EnemiesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/personas/': typeof PersonasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/equipments'
    | '/fusion'
    | '/items'
    | '/quests'
    | '/skills'
    | '/system'
    | '/characters/$characterId'
    | '/enemies/$enemyId'
    | '/locations/$locationId'
    | '/personas/$personaId'
    | '/characters/'
    | '/enemies/'
    | '/locations/'
    | '/personas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/equipments'
    | '/fusion'
    | '/items'
    | '/quests'
    | '/skills'
    | '/system'
    | '/characters/$characterId'
    | '/enemies/$enemyId'
    | '/locations/$locationId'
    | '/personas/$personaId'
    | '/characters'
    | '/enemies'
    | '/locations'
    | '/personas'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/equipments'
    | '/fusion'
    | '/items'
    | '/quests'
    | '/skills'
    | '/system'
    | '/characters/$characterId'
    | '/enemies/$enemyId'
    | '/locations/$locationId'
    | '/personas/$personaId'
    | '/characters/'
    | '/enemies/'
    | '/locations/'
    | '/personas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EquipmentsRoute: typeof EquipmentsRoute
  FusionRoute: typeof FusionRoute
  ItemsRoute: typeof ItemsRoute
  QuestsRoute: typeof QuestsRoute
  SkillsRoute: typeof SkillsRoute
  SystemRoute: typeof SystemRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  EnemiesEnemyIdRoute: typeof EnemiesEnemyIdRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
  PersonasPersonaIdRoute: typeof PersonasPersonaIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  EnemiesIndexRoute: typeof EnemiesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PersonasIndexRoute: typeof PersonasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fusion': {
      id: '/fusion'
      path: '/fusion'
      fullPath: '/fusion'
      preLoaderRoute: typeof FusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipments': {
      id: '/equipments'
      path: '/equipments'
      fullPath: '/equipments'
      preLoaderRoute: typeof EquipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas/': {
      id: '/personas/'
      path: '/personas'
      fullPath: '/personas/'
      preLoaderRoute: typeof PersonasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enemies/': {
      id: '/enemies/'
      path: '/enemies'
      fullPath: '/enemies/'
      preLoaderRoute: typeof EnemiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas/$personaId': {
      id: '/personas/$personaId'
      path: '/personas/$personaId'
      fullPath: '/personas/$personaId'
      preLoaderRoute: typeof PersonasPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId': {
      id: '/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enemies/$enemyId': {
      id: '/enemies/$enemyId'
      path: '/enemies/$enemyId'
      fullPath: '/enemies/$enemyId'
      preLoaderRoute: typeof EnemiesEnemyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EquipmentsRoute: EquipmentsRoute,
  FusionRoute: FusionRoute,
  ItemsRoute: ItemsRoute,
  QuestsRoute: QuestsRoute,
  SkillsRoute: SkillsRoute,
  SystemRoute: SystemRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  EnemiesEnemyIdRoute: EnemiesEnemyIdRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
  PersonasPersonaIdRoute: PersonasPersonaIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  EnemiesIndexRoute: EnemiesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PersonasIndexRoute: PersonasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
